// Code generated by github.com/CognexVisionSoftware/go-jsonschema, DO NOT EDIT.

package test

type RefToMap struct {
	// MyThing corresponds to the JSON schema field "myThing".
	MyThing Thing `json:"myThing,omitempty,omitzero" yaml:"myThing,omitempty" mapstructure:"myThing,omitempty"`
}

type Thing map[string]float64
